### ISSUE TITLE
Use with Harmony Hub

### ISSUE THREAD

**Issue by ThronEisvogel** [dimagoltsman/content-card-remote-control#2]
Hey!
First of all, thank you for creating the plugin. I am still a noob but I'd like to tweak the plugin so that I can use it with a Harmony Hub but I dont get it working. I created a remote_template folder in which I put a firetv template
Here are some pictures: https://imgur.com/a/1uUpKUC , https://imgur.com/a/istyKED
I'm definitely not familiar with Java Script so I probably did something wrong in the "**remote-html.js**" and/or "**content-card-remote-control.js**" file: https://pastebin.com/Jgqs7zS7 ,
https://pastebin.com/UCeg60DB .
I tried to change some commands but obviously it did not work out.
The path of the template: "**\www\community\content-card-remote-control\remote_template\firetv**".
The Harmony config file shows every command so it should be possible to integrate them into the plugin right?
Harmony.config:
https://pastebin.com/SUNh2jWn
I would be glad if you could help me 👍

**Comment by dimagoltsman** [comment]
you are welcome to PR :)
